export const USERDRINKS_ADD_ROUTE = "addDrinkToBasket/"
export const USERDRINKS_DELETE_ROUTE = "deleteUserDrink/"
export const USERDRINKS_CHANGE_ROUTE = "changeUserDrinkAmount/"
export const USERDRINKS_GET_ALL_ROUTE = "getAllUserDrinks/"
export const USERDRINKS_GET_ROUTE = "getSpecificUserDrink/"
export const USERDRINKS_BUY_ROUTE = "buyDrinks/"